FROM python:3.11
EXPOSE 5001
WORKDIR /app
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "sh", "-c", "flask db upgrade && flask run --host 0.0.0.0 --port 5001" ]