FROM python:3.11-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["sh", "-c", "flask db upgrade && gunicorn -b 0.0.0.0:5002 'app:create_app()'"]